name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Gradle Dependencies Cache
        uses: actions/cache@v3.2.1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

      - name: Setup Plugin Verifier IDEs Cache
        uses: actions/cache@v3.2.1
        with:
          path: ~/.pluginVerifier/ides
          key: ${{ runner.os }}-plugin-verifier-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

      - uses: Project-Env/project-env-github-action@v1.3.1

      - run: |
          echo "ORG_GRADLE_PROJECT_githubUsername=${{ github.actor }}" >> $GITHUB_ENV
          echo "ORG_GRADLE_PROJECT_githubPassword=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Run Linters and Test
        run: gradle check

      - name: Verify Plugin Completeness
        run: gradle verifyPlugin

      - name: Build Plugin
        run: gradle buildPlugin

      - name: Verify Binary Compatibility
        run: gradle runPluginVerifier -Pplugin.verifier.home.dir=~/.pluginVerifier

      - name: Sonar
        if: ${{ github.actor != 'dependabot[bot]' }}
        run: gradle sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}